---
# WireGuard with Docker configuration
wireguard:
  # WireGuard internal network
  internal_subnet: "10.13.13.0"
  server_port: 51820
  timezone: "America/Bogota"
  
  # Number of peers/clients to generate
  peers: 3
  
  # DNS for clients
  peer_dns: "auto"  # Can also be "1.1.1.1" or "8.8.8.8"
  
  # Configuration directory on the server
  config_dir: "/root/wireguard"

# Docker configuration
docker:
  # docker-compose version
  compose_version: "2.24.0"
