---
- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages
  apt:
    name:
      - wireguard
      - wireguard-tools
      - ufw
      - qrencode
    state: present

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Create directory for WireGuard keys
  file:
    path: /etc/wireguard/keys
    state: directory
    mode: '0700'
    owner: root
    group: root

- name: Create directory for client configurations
  file:
    path: /etc/wireguard/clients
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Generate server private key
  shell: wg genkey
  register: server_private_key
  changed_when: false
  no_log: true

- name: Generate server public key
  shell: echo "{{ server_private_key.stdout }}" | wg pubkey
  register: server_public_key
  changed_when: false
  no_log: true

- name: Save server private key
  copy:
    content: "{{ server_private_key.stdout }}"
    dest: /etc/wireguard/keys/server-private.key
    mode: '0600'
    owner: root
    group: root
  no_log: true

- name: Save server public key
  copy:
    content: "{{ server_public_key.stdout }}"
    dest: /etc/wireguard/keys/server-public.key
    mode: '0644'
    owner: root
    group: root

- name: Generate keys for clients
  include_tasks: generate_client_keys.yml
  loop: "{{ wireguard.clients }}"
  loop_control:
    loop_var: client

- name: Create WireGuard server configuration
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: '0600'
    owner: root
    group: root
  notify:
    - restart wireguard

- name: Generate configurations for clients
  include_tasks: generate_client_configs.yml
  loop: "{{ wireguard.clients }}"
  loop_control:
    loop_var: client

- name: Configure UFW firewall
  include_tasks: configure_firewall.yml
  when: firewall.enabled | default(true)

- name: Enable and start WireGuard
  systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started
