---
- name: Actualizar cache de paquetes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Instalar dependencias para Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
    state: present

- name: Agregar clave GPG de Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Agregar repositorio de Docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Instalar Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
    state: present

- name: Iniciar y habilitar Docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Agregar usuario ubuntu al grupo docker
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Descargar docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v{{ docker.compose_version }}/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
    owner: root
    group: root

- name: Crear enlace simbólico para docker-compose
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link

- name: Crear directorio para WireGuard
  file:
    path: "{{ wireguard.config_dir }}"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Crear directorio para docker-compose
  file:
    path: /root/docker-wireguard
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Crear archivo docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /root/docker-wireguard/docker-compose.yml
    mode: '0644'
    owner: root
    group: root
  notify:
    - restart wireguard container

- name: Configurar firewall para WireGuard
  ufw:
    rule: allow
    port: "{{ wireguard.server_port }}"
    proto: udp

- name: Habilitar UFW
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Permitir SSH en firewall
  ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Permitir HTTPS en firewall
  ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Permitir servidor de configuraciones en firewall
  ufw:
    rule: allow
    port: '8080'
    proto: tcp

- name: Iniciar contenedor WireGuard
  shell: |
    cd /root/docker-wireguard
    docker-compose up -d
  register: docker_result

- name: Esperar a que el contenedor esté corriendo
  shell: docker ps | grep wireguard | grep Up
  register: container_status
  until: container_status.rc == 0
  retries: 30
  delay: 2

- name: Esperar a que se generen las configuraciones de peers
  shell: |
    # Esperar a que se cree al menos un directorio de peer
    timeout=60
    while [ $timeout -gt 0 ]; do
      if [ -d "{{ wireguard.config_dir }}/peer1" ] && [ -f "{{ wireguard.config_dir }}/peer1/peer1.conf" ]; then
        echo "Configuraciones generadas"
        exit 0
      fi
      sleep 2
      timeout=$((timeout-2))
    done
    echo "Timeout esperando configuraciones"
    exit 1
  register: config_wait
  changed_when: false

- name: Configurar script de descarga de configuraciones
  template:
    src: download-configs.sh.j2
    dest: /root/download-configs.sh
    mode: '0755'
    owner: root
    group: root

- name: Crear servidor HTTP simple para descargar configuraciones
  template:
    src: serve-configs.py.j2
    dest: /root/serve-configs.py
    mode: '0755'
    owner: root
    group: root

- name: Debug - Mostrar logs del contenedor WireGuard
  shell: docker logs wireguard --tail 20
  register: container_logs
  changed_when: false

- name: Mostrar logs del contenedor
  debug:
    msg: "{{ container_logs.stdout_lines }}"

- name: Debug - Verificar estructura de directorios
  shell: find {{ wireguard.config_dir }} -type f -name "*.conf" -o -name "*.png" 2>/dev/null || echo "No se encontraron archivos de configuración"
  register: config_files
  changed_when: false

- name: Mostrar archivos de configuración encontrados
  debug:
    msg: "{{ config_files.stdout_lines }}"

- name: Instalar Python3 para el servidor HTTP
  apt:
    name: python3
    state: present

- name: Verificar que las configuraciones existen antes de iniciar servidor HTTP
  shell: ls -la {{ wireguard.config_dir }}/peer*/
  register: peer_check
  changed_when: false

- name: Mostrar configuraciones encontradas
  debug:
    msg: "{{ peer_check.stdout_lines }}"

- name: Matar procesos previos del servidor de configuraciones
  shell: pkill -f serve-configs.py
  register: pkill_result
  failed_when: false
  changed_when: pkill_result.rc == 0

- name: Iniciar servidor HTTP para configuraciones (puerto 8080)
  shell: |
    cd {{ wireguard.config_dir }}
    nohup python3 /root/serve-configs.py > /var/log/config-server.log 2>&1 &
    echo $! > /var/run/config-server.pid
  changed_when: true

- name: Verificar que el servidor HTTP está corriendo
  shell: netstat -tlnp | grep :8080
  register: http_server_check
  changed_when: false
  ignore_errors: yes

- name: Mostrar estado del servidor HTTP
  debug:
    msg: "{{ 'Servidor HTTP corriendo en puerto 8080' if http_server_check.rc == 0 else 'Error: Servidor HTTP no está corriendo' }}"
